import type { Metadata } from "next";
import "./globals.css";
import { share, shareTech, shareTechMono, turretRoad } from "./fonts";
import NavBar from "./ui/nav/nav-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${share.variable} ${shareTech.variable} ${shareTechMono.variable} ${turretRoad.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
